### ISSUE TITLE
Development stopped?

### ISSUE THREAD

**Issue by SystematicError** [kognise/repl.it-mobile#11]
So is this project discontinued? No more repl.it mobile?

And if so can you specify it in the README.md too?

**Comment by Vandesm14** [comment]
I think it was either halted or completely discontinued because repl.it has "proper" mobile friendliness for their website. Also because Kognise, the developer, needed a break or something.

**Comment by SystematicError** [comment]
Indeed repl.it is quite mobile friendly however some things could be improved

Also I believe it was stopped due to other reasons

**Comment by hackermondev** [comment]
thinking about reviving this project and creating my own 🤷 @SystematicError what are some of the things you think can be improved on the mobile version.

**Comment by SystematicError** [comment]
I would love for the app to prioritise the compiler, web view tab, and bash terminal over looks.

In the previous app the looks were prioritised and the project stopped before any working version was released.
