### ISSUE TITLE
Archive this?

### ISSUE THREAD

**Issue by hackermondev** [kognise/repl.it-mobile#20]
Replit already released a [official mobile app](https://play.google.com/store/apps/details?id=com.replit.twa) and it doesn't look like this is still in development so you should probably archive this.

**Comment by vexcited** [comment]
their official app is just the pwa version of their website so yea it's not that good for me.

i think it will be better to do a real app, like everything is buggy for me on their app...

**Comment by hackermondev** [comment]
Well if everything is buggy for you, you should probably report it at https://replit.canny.io so they can fix it.

**Comment by kognise** [comment]
![](https://doggo.ninja/T1zRwq.png)
